apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dormwatch-front-v1-secret
  namespace: dormwatch-front-v1
spec:
  encryptedData: {}
  template:
    metadata:
      name: dormwatch-front-v1-secret
      namespace: dormwatch-front-v1
    type: Opaque
